dbt_commandprompt_project:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: DESKTOP-RC4C5PQ\SQL2022
      port: 1433
      database: dbt_projects
      schema: analytics
      windows_login: True
      trust_cert: True